# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bt1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bt1

  target 'bt1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bt1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'bt1-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bt1-tvOS

  target 'bt1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'FBSDKLoginKit'
